### ISSUE TITLE
Installation stucks after version 4.10.0

### ISSUE THREAD

**Issue by ozum** [bevry/badges#57]
Hi,

`npm install badges` stucks after version `4.10.0` for some projects, but not others.

When I investigate the problem, I saw `badges` has exact same `dependencies` and `devDependencies` in package.json from `4.10.0` on. One or more development related modules such as `eslint`, `typescript`, `prettier`, `typedoc` installed by `badges` collide with my projects'.

I thought they were added by accident. Is there a reason to add `eslint`, `typescript`, `prettier`, `typedoc` and other development related libraries to `dependencies`?

Thanks,

**Comment by balupton** [comment]
working on it

**Comment by balupton** [comment]
found the culprit

https://github.com/bevry/make-deno-edition/commit/d7383900c037314557caf0986d011ef6fbbf314a#diff-21e9ddd93162651bd36f6e5bbfca8460L443

fixing all the bevry packages now

**Comment by balupton** [comment]
let me know if v4.12.0 releasing now https://travis-ci.com/github/bevry/badges/jobs/351785601 fixes it

**Comment by ozum** [comment]
Thanks, it is working now.
