### ISSUE TITLE
Badges are slow and fail

### ISSUE THREAD

**Issue by bradennapier** [bevry/badges#7]
Why are the badges taking like 3-5 seconds or more to load and most of the time at leastone fails completely!?

![image](https://user-images.githubusercontent.com/15365418/27249576-aa4c37fa-52cd-11e7-980e-ea7f54325490.png)

**Comment by bradennapier** [comment]
![image](https://user-images.githubusercontent.com/15365418/27249581-b9700c3e-52cd-11e7-9789-c299ec5df1f8.png)

**Comment by bradennapier** [comment]
it has not loaded the badges properly in the last 5+ updates

**Comment by RobLoach** [comment]
Shield could be slow.

**Comment by balupton** [comment]
All this project does is render the badges. Serving the badges is handled by whichever host is serving them. As @robloach has stated, we use shields.io for most of our badges. Here is there GitHub if you want to post, a hopefully more polite, issue there: https://github.com/badges/shields

**Comment by bradennapier** [comment]
@balupton my bad!  I did not try to sound rude or anything, was multi-tasking and just posted it asap in case something was up or I was doing something incorrectly.  It appears to have been due to a travisci build running -- once it finished the badges were fast which was a bit odd!

Thanks for the package, automating all this stuff definitely makes handling micro-package environments far nicer.
